build.sh

This updates the build script to:
1. Make sure the dist folder variable is not empty (for safety)
2. Fixes an error if the checkout is done on a non-empty dist folder
3. Uses git rm/clean to clear out existing files so that deleted files get removed from the github pages
I just used this to update the site.

Updated build script to remove old files

---

src/code/views/app-view.coffee
src/code/views/node-edit-view.coffee
src/code/views/node-view.coffee
src/code/views/node-well-view.coffee
src/code/views/proto-node-view.coffee
src/code/views/proto-nodes.coffee
src/stylus/node-edit.styl

The node edit image select now has two option groups - built-in images and remote images.  Under the remote images option group there is an 'Add Remote...' option that when selected shows a remote url input and a button to add the image.  When the add image button is clicked the img url is tested to see if it can be loaded and if it can the image is changed and is also added to the palette to the left of the blank option.
I also added the ability to click on an image in the palette and immediately update the selected node to that image.  This was not in the story but I thought it would be interesting to test.

Adds a remote image option to the node edit view

---

src/assets/json/serialized.json
src/code/models/link-manager.coffee
src/code/utils/google-drive-io.coffee
src/code/views/app-view.coffee
src/code/views/google-file-view.coffee
src/code/views/node-edit-view.coffee
src/code/views/node-well-view.coffee
src/code/views/proto-nodes.coffee
src/code/views/status-menu-view.coffee
src/stylus/status-menu-view.styl
test/node-list-test.coffee

Along with a new button and google drive open and save buttons this also:
1. Adds a version number, the filename and the state of the node well to the serialized data.  The version number can be used in the future and the filename is used when serializing to the url.  
2. Adds a load listener to the link manager that is used in the app view to both load the saved palette and replace the onAddRemoteImage() functionality 
3. Moves the filename into the link manager and adds a listener that the app view subscribes to so that it can update its filename state which is passed down to the google file view
4. Removes the node well click handler that updates the selected node image

Added new button and google drive open and save buttons

---

src/code/utils/google-drive-io.coffee

The auto token is now saved in case the user picks a new user to authorize in the popup dialog.

Fixes clicking open when have two logged in users in Chrome [#93911702]

---

src/stylus/components/image-picker.styl
src/stylus/components/inspector-panel.styl
src/stylus/components/node.styl
src/stylus/components/proto-node.styl
src/stylus/components/top-node-palette.styl

Any non-square images were being "squished" to squares in the css.
Test by dragging in the following image:
http://upload.wikimedia.org/wikipedia/commons/5/58/Sunset_2007-1.jpg

Fixed distorted rectangular images [#94094714]

---

src/code/models/link-manager.coffee
src/code/utils/lang/us-en.coffee
src/code/views/link-view.coffee
src/code/views/node-view.coffee
src/stylus/components/node.styl

One thing which will need to described and built up is the idea of nodeViewStates.
These will be transient states related to selection for the Nodes in the link-view.
Our current model of selection in link-view is week.  This PR includes some an initial (inadequate) attempt to address some of this.
This PR is for https://www.pivotaltracker.com/story/show/93909154: "When a component is dragged from the palette to the model, it should have a name of 'untitled' and the title should immediately be editable with the cursor focus in the title."

In-place edit  for node titles. [#93909154]

---

src/code/mixins/node-title.coffee
src/code/views/node-inspector-view.coffee
src/code/views/node-view.coffee

The inspector title behaved differently form the direct node title editing.
This unifies the string truncation and other behaviors in both contexts.
https://www.pivotaltracker.com/story/show/93911110

[#93911110] unify direct & inspector editing for node title.

---

src/code/mixins/app-view.coffee
src/code/models/link.coffee
src/code/models/node.coffee
src/code/models/simulation.coffee
src/code/views/app-view.coffee
src/code/views/global-nav-view.coffee
src/stylus/components/global-nav.styl
test/simulation-test.coffee

This PR is for the PT Story: [Evaluate model values #95934926](https://www.pivotaltracker.com/story/show/95934926)
The commits in here are mostly for the Simulation class, and its tests.
An instance of the Simulation class is created with simulation options for duration, time step, and nodes.
This creates a short-lived object created once for each run.
Following a DCI pattern, the Simulation modifies the participating nodes,
and binds them to an integration function, and initializes there state.  We may support
different integration methods in the future. The Current implementation is a simple forward Euler, which seems to work quite well in the tests.
Simulation is the only context in where nodes to have state history, and an integration function. This Simulation class is an attempt to …

Numerical modeling

---

src/code/app.coffee
src/code/mixins/app-view.coffee
src/code/models/codap-connect.coffee
src/code/models/link-manager.coffee
src/code/utils/undo-redo.coffee
src/code/views/document-actions-view.coffee
test/node-list-test.coffee

This PR uses a new CODAP API to allow CODAP to control the app's undo/redo history.
Each time we perform an undoable event, we notify CODAP of this. CODAP can then send us
undo and redo commands, which we perform using our own undo-redo manager.
Our undoable events are stored in CODAP's undo stack, which closely mimics this undo stack, so when CODAP calls 'undo', it pops off the action from CODAP's stack, and causes BuildingModels to pop off the action from its stack. The two will track identically.
We also add the ability for CODAP to inform BuildingModels that it is using its own undo system (which it doesn't always), so that BuildingModels can hide its undo UI. (Note that this doesn't affect whether we send the undoableActionPerformed messages, since these are side-effect free if CODAP …

Codap undo redo

---

src/code/models/palette-manager.coffee
src/code/views/image-metadata-view.coffee
src/code/views/palette-inspector-view.coffee
src/code/views/preview-image-dialog-view.coffee

The image metadata cache wasn't being saved & loaded correctly.
The main issue was that the onLoad handler wasn't handling it.
Additionally when images were loaded from the local machine, the metadata was being added to the wrong image.
https://www.pivotaltracker.com/story/show/100136692

Fix missing metadata bug: [#100136692]

---

src/code/app.coffee
src/code/mixins/draggable.coffee
src/code/models/image-manager.coffee
src/code/utils/lang/us-en.coffee
src/code/views/app-view.coffee
src/code/views/image-browser-view.coffee
src/code/views/link-view.coffee
src/code/views/palette-inspector-view.coffee
src/code/views/palette-item-view.coffee
src/code/views/preview-image-dialog-view.coffee
src/stylus/components/palette-inspector.styl

The image browsing dialog now has to support two modes.
In the first mode we are just adding images to the Palette. Nothing is being dragged on the canvas. Its current functionality is great -- we just keep the dialog open so that the user can add more and more images.
The second case is more modal. According to this story: https://www.pivotaltracker.com/story/show/95933006  we need to use the dialog to pick one single image to be dropped onto the canvas (and also added to palette).  
The ImageManager is an attempt to centralize the logic for configuring / showing / hiding the dialog box.  Its also possible to supply a call-back hook now so that the interrupted operation (dragging) can continue after the image is selected.

Drag add image

---

src/code/models/image-manager.coffee
src/code/models/palette-manager.coffee
src/code/views/palette-inspector-view.coffee

Fixes bug where 'new' in progress meta-data is shown next to selected
palette item, that causes confusion.
https://www.pivotaltracker.com/n/projects/1263626/stories/95933006

Add  methods to deselect items in Palette.

---

src/code/mixins/app-view.coffee
src/code/models/codap-connect.coffee
src/code/models/link-manager.coffee
src/code/stores/codap-store.coffee
src/code/utils/undo-redo.coffee
src/code/views/document-actions-view.coffee

We now only show the Run button if we are embedded in CODAP. We do this by listening to a successful phone call to CODAP, and setting state via a new codap-store.
Also refactored how we respond to CODAP asking us to hide the undo/redo buttons into the codap-store.
https://www.pivotaltracker.com/story/show/101447232

Show Run button only in codap

---

src/code/stores/graph-store.coffee
src/code/stores/palette-delete-dialog-store.coffee
src/code/utils/undo-redo.coffee
src/code/views/node-view.coffee

Allows us to batch multiple undoable commands into a single command that can be undone or redone in one click.
https://www.pivotaltracker.com/story/show/101973812
@knowuh Let me know if you have a better solution for the `setTimeout` that is called in `endCommandBatch`. Without it, if we call
@undoManger.startCommandBatch()
PaletteStore.actions.deleteSelected()
... anything else
@undoManger.endCommandBatch()
then `deleteSelected` gets called after `endCommandBatch`, because it uses an async callback.

Batch undo redo

---

src/code/data/migrations/03_add_semi_quant_editing.coffee
src/code/data/migrations/migrations.coffee
src/code/models/node.coffee
src/code/stores/graph-store.coffee
src/code/utils/lang/us-en.coffee
src/code/views/node-value-inspector-view.coffee
src/stylus/components/inspector-panel.styl
test/migrations-test.coffee

This adds a toggleable panel that allows a user to switch between defining
a node's value semi-quantitatively (low-high) or with numbers.
This adds a new property to a node, because any node that has been defined
in one way should keep being defined that way when the user re-opens the
editing panel.
The property `valueDefinedSemiQuantitatively` is a bit of a mouthful,
but it describes the intent. Note that this only describes how it's being
defined, nothing about the actual value changes.
[#97759284]

Add editing panel for defining node values with words

---

package.json
src/code/data/migrations/06_add_palette_references.coffee
src/code/data/migrations/migrations.coffee
src/code/models/node.coffee
src/code/stores/graph-store.coffee
src/code/stores/palette-store.coffee
src/code/utils/importer.coffee
src/code/views/graph-view.coffee
test/loading-serialization-test.coffee
test/migrations-test.coffee

To save space in our serialized `.json` files, GraphNodes now reference PaletteItems by their UUID.   
When reconstituted via load the GraphNodes load images via the referenced PaletteItem.
This is mostly a migration and a few serialization tests.
@sfentress could you please review when you get a chance?
https://www.pivotaltracker.com/story/show/100138582

Saving references to a graph nodes PaletteItem (& tests)   [#100138582]

---

src/code/stores/simulation-store.coffee
src/code/utils/lang/us-en.coffee
src/code/views/document-actions-view.coffee
src/code/views/dropdown-view.coffee
src/code/views/simulation-panel-view.coffee
src/stylus/components/document-actions-view.styl
src/stylus/components/menu.styl
src/stylus/components/simulation-panel.styl
src/stylus/components/value-slider.styl
src/stylus/mixins/blender-box-colors.styl
src/stylus/mixins/fonts.styl

This adds the Simulation Panel UI, as requested by https://www.pivotaltracker.com/story/show/103626652
No new functionality exists in this panel, only the run button works. The other buttons show disabled states, but the sliders don't show a disabled state, even though they are non-functional. If we think this will be confusing, I can add a disabled state to the sliders for the window of time where we have non-useful sliders.
I would normally want to keep working on this branch to add more functionality to the panel, but since it contains features useful to @knowuh, and since @ddamelin has indicated that the panel alone is a useful feature (to allow users to imagine future development) I think this could be ready as is?

Simulation panel

---

src/code/app.coffee
src/code/mixins/app-view.coffee
src/code/stores/simulation-store.coffee
src/code/views/app-view.coffee
src/code/views/document-actions-view.coffee
src/code/views/simulation-panel-view.coffee
src/code/views/value-slider-view.coffee
src/stylus/components/simulation-panel.styl
src/stylus/components/value-slider.styl
src/stylus/mixins/blender-box-colors.styl

This adds an editable range to the slider, which is then used to set the number of steps the model will run for.
The editable range slider is modeled after the existing one in the node properties panel.
This also includes a slight refactoring of the slider. This isn't a necessary refactoring, but after a fair bit of time delving into best practices for React components, I think it makes sense.
This doesn't quite complete https://www.pivotaltracker.com/story/show/102293096, but it adds the most valuable feature (settable number of steps), and I think it makes sense as its own PR to encapsulate the slider changes.
https://www.pivotaltracker.com/story/show/102293096
https://www.pivotaltracker.com/story/show/102606120
@knowuh When you have a chance, can you take a look?

Simulation editable steps

---

src/code/models/node.coffee
src/code/stores/graph-store.coffee
src/code/views/graph-view.coffee
src/code/views/node-value-inspector-view.coffee
src/code/views/node-view.coffee
src/code/views/value-slider-view.coffee
src/stylus/components/value-slider.styl

Also part of https://www.pivotaltracker.com/story/show/102293636.  This time we have connected the sliders in the graph window to the nodes initial-values.  
There is more work to be done, but I thought I would put this up to talk about.  At the time of this PR, I also deployed to http://concord-consortium.github.io/building-models/
Changes:  
* Sliders only show up for independent variables, or accumulators.
* Sliders adjust the 'initial value' of nodes.
* The Value text-edit field is the 'current-value' -- which is usually just the initial value.

Sliders are connected to node initial-values.  [#102293636]

---

src/code/stores/graph-store.coffee
src/code/stores/palette-delete-dialog-store.coffee
src/code/utils/undo-redo.coffee

This PR turns undo and redo into Reflux actions, and along the way fixes several bugs:
1. Closing the delete dialog without deleting anything called undo() on the last action
2. Opening the delete dialog, adding a new image, then cancelling and closing the dialog wasn't correctly removing the newly-added image
3. Even when the newly-added image was correctly removed, the use could re-add the item via the "redo" button, which would be unexpected as the user never explicitly undid anything
4. Clicking away from a node without changing its title was adding an empty action to the undo stack. (This was unrelated to the above, but fixed anyway.)
@knowuh When you have a little time, could you hammer on this for a new minutes and see if you catch any edge-cases where I might have added a …

Make undo and redo into actions, fix several bugs

---

src/code/actions/graph-actions.coffee
src/code/actions/import-actions.coffee
src/code/data/migrations/08_add_simulation_settings.coffee
src/code/data/migrations/migrations.coffee
src/code/stores/app-settings-store.coffee
src/code/stores/graph-store.coffee
src/code/stores/palette-store.coffee
src/code/stores/simulation-store.coffee
src/code/utils/importer.coffee
test/loading-serialization-test.coffee
test/migrations-test.coffee
test/stores/simulation-store-test.coffee

* Import is now an action.
* Broke out  graph-actions to resolve circular dependencies.
* Instead of listening for onLinksChange or onModelChange, just listen for onGraphChanged.
* Moved CODAP initialization into _sendSimulationData, to isolate that dependency.
* Broke out _setUnitsNames method, initially so names could be calculated after loading from serialized form.  Even though its overlaps functionally with `time-units-test.coffee`, I made a separate test for it.
There were also new migrations and serializations added.
See: https://www.pivotaltracker.com/story/show/104657406 for PT story.

Reflux actions for loading. Serialize simulation [#104657406]

---

src/assets/sage.html

Frieda encountered this tonight while trying to use Sage from   Lara(https) → Codap(https) → Sage(https).

Use protocol-relative paths for CFM urls; avoid mixed-content errors.

---

src/code/actions/codap-actions.coffee
src/code/models/codap-connect.coffee
src/code/stores/graph-store.coffee

If we receive the new event `standaloneUndoModeAvailable`, we show
our own undo-redo buttons, but any button press (or ctr-z) gets sent
directly to CODAP to handle. CODAP will then try to execute an undo
or redo, which may in turn send the request back down to us.
When CODAP sends an undo or redo event back down to us, we will always
try to execute it.

If CODAP is standalone, send undo requests to CODAP

---

package.json
src/code/data/migrations/01_base.coffee
src/code/data/migrations/02_add_relations.coffee
src/code/data/migrations/03_add_semi_quant_editing.coffee
src/code/data/migrations/04_add_min_max.coffee
src/code/data/migrations/05_add_settings_and_cap.coffee
src/code/data/migrations/06_add_palette_references.coffee
src/code/data/migrations/07_add_diagram_only_setting.coffee
src/code/data/migrations/08_add_simulation_settings.coffee
src/code/data/migrations/09_update_duration_settings.coffee
src/code/data/migrations/10_add_speed_and_cap.coffee
src/code/data/migrations/11_simulation_engine_settings.coffee
src/code/data/migrations/migration-mixin.coffee
src/code/data/migrations/migrations.coffee
test/loading-serialization-test.coffee
test/migrations-test.coffee

@knowuh This updates all our old migration numbers to SemVer.
I can't see a problem with updating our old migration numbers. We convert the versions in the saved doc to their equivalent semvers before deciding to update, so we shouldn't run any migrations twice. However, I may be missing something.

Switch data versions to use SemVer

---

src/code/data/migrations/12_add_minigraphs_visibility.coffee
src/code/data/migrations/migrations.coffee
src/code/mixins/app-view.coffee
src/code/models/node.coffee
src/code/stores/app-settings-store.coffee
src/code/stores/graph-store.coffee
src/code/views/app-view.coffee
src/code/views/graph-view.coffee
src/code/views/inspector-panel-view.coffee
src/code/views/node-svg-graph-view.coffee
src/code/views/node-view.coffee
src/code/views/simulation-inspector-view.coffee
test/loading-serialization-test.coffee
test/migrations-test.coffee

With this change, the `GraphStore` listens to the simulation events, and pushes frame data into
each `Node` object when we have new simulation data.
With this data, we can swap out the internal node image for a new `node-svg-graph-view` when the minigraph checkbox is checked.
The minigraph state is loaded and serialized, but the frame data is not.
Note that we see some similar speed issues as CODAP when we manipulate the slider while the
model is running. Now that this effect is local, we can more easily profile what's going on.
@knowuh or @dougmartin can you take a look sometime when you have a moment?

Add minigraphs to nodes

---

src/code/models/relationship.coffee
src/code/models/simulation.coffee
src/code/stores/simulation-store.coffee
src/code/utils/lang/us-en.coffee
src/code/views/link-relation-view.coffee
src/code/views/relation-inspector-view.coffee
src/code/views/simulation-run-panel-view.coffee
src/code/views/svg-graph-view.coffee
src/stylus/components/simulation-run-panel.styl
src/stylus/components/svg-graph-view.styl
test/loading-serialization-test.coffee
test/migrations-test.coffee
test/relationship-test.coffee

This adds the notion of a relationship that can be undefined. All links start out with undefined relationships, and the user must select an option from the relation editing panel to define it.
A model can run when there are undefined relationships (it treats them as not existing), but there now must be at least one defined relationship for the model to run.

Add undefined relationships

---

src/code/models/node.coffee
src/code/stores/graph-store.coffee
src/code/views/node-view.coffee
test/node-list-test.coffee

This
1. recognizes if nodes are in a cycle
2. shows enabled sliders before running a simulation for independent nodes, nodes in a cycle, and collectors
3. grays out sliders for nodes in a cycle and collectors during simulation
4. considers any node with only undefined inbound links as being a independent node
and tests are added.
https://www.pivotaltracker.com/story/show/116538381
https://www.pivotaltracker.com/story/show/117075519

Hide dependent sliders

---

package.json
src/code/models/codap-connect.coffee

Fixes bug: https://www.pivotaltracker.com/story/show/121420841
We found that Sage modeler was (a) issuing createCases requests to CODAP sometimes sending zero cases, and (b) updating a row in the parent table unnecessarily. The value that was being updated was the count of the child cases, a value that could be captured with a formula. So, we change the definition of the attribute to include the formula and comment out the update altogether.
There is still a lot of unnecessary chatter between Sage and CODAP, the removal of which could improve things some more. For example, CODAP sends many clearUndo and clearRedo requests, that it should not. But, on a reasonable machine, CODAP can keep up with graph updates, while a
run is executing and the slider is being manipulated.
To get a working …

Improve codap streaming

---

src/assets/codap-ivy-fonts.css
src/assets/test.html
src/code/utils/js-plumb-diagram-toolkit.coffee
src/code/views/graph-view.coffee
src/code/views/node-svg-graph-view.coffee
src/code/views/node-view.coffee
src/code/views/svg-graph-view.coffee
src/code/views/value-slider-view.coffee
src/stylus/components/node.styl
src/stylus/components/value-slider.styl

This adds a thermometer-style vertical slider to the right, and moves the two existing action circle.
The slider view now has many more options for horizontal, vertical, fillable and not. This is probably useless, as we are no longer using it anywhere else, now that the speed slider has gone, but we might as well keep it until maintaining these options becomes too painful.
The slider is shorter than what @ddamelin's mockups showed, as the apparent intent in the mockups was to make the thermometer level to be exactly aligned with the minigraph.
[#132117711] https://www.pivotaltracker.com/story/show/132117711
[#132832351] https://www.pivotaltracker.com/story/show/132832351
[#132117775] https://www.pivotaltracker.com/story/show/132117775

Vertical slider

---

gulp/config.js
gulp/tasks/assets.js
src/assets/index.html
src/assets/sage.html

@knowuh This is a straw-man idea for cache-busting, using query parameters on app.js and app.css that are unique per deployment (i.e. request `app.js?v={COMMIT_SHA}`).
There may well be other methods of dealing with this. Thoughts/conversation appreciated.
https://www.pivotaltracker.com/story/show/134090627

Add cache-busting query to app.js and app.css

---

src/code/models/codap-connect.coffee
src/code/stores/graph-store.coffee
src/code/stores/simulation-store.coffee
src/code/utils/time-units.coffee
src/code/views/node-view.coffee
test/loading-serialization-test.coffee
test/simulation-test.coffee

An in-progress branch.
'Simulation' is been decoupled from sending to CODAP in this branch.  It also includes an improvement to how we are listening to simulation changes in the simulation tests.
Here are some related PT stories:
User can collect a single data point and send it to CODAP when there are no collectors.
https://www.pivotaltracker.com/story/show/133207443
User can turn on "recording" to send a stream of data when no collectors are present.
https://www.pivotaltracker.com/story/show/133207187

Record simulation changes

---

src/code/stores/simulation-store.coffee

These commits address state bugs change in the simulation panel.
* should update the recording buttons in the simulation panel when the diagram starts using collectors.
* should stop recording when the diagram gets a collector.
* should stop recording when the simulation panel is closed.
If you have a second to review @sfentress 
Thanks!

Some simulation panel fixes

---

src/code/models/node.coffee
src/code/utils/colors.coffee
src/code/utils/lang/us-en.coffee
src/code/views/color-picker-view.coffee
src/code/views/graph-view.coffee
src/code/views/node-svg-graph-view.coffee
src/code/views/node-view.coffee
src/code/views/value-slider-view.coffee
src/stylus/components/value-slider.styl

This PR lets the data colors for the mini-graph and the sliders be adjusted dynamically.
When the simulation is being recorded, the data is displayed in CODAP orange.
Otherwise is gray.
@sfentress please review when you get a chance.

Gray mini graphs and slider bars when not recording.

---

src/code/stores/simulation-store.coffee
src/code/views/value-slider-view.coffee

This eliminates the issue where the simulation runs multiple times with the same value, leading to straight lines in the graphs.
It also seems to have a positive effect on the feeling of "lag" when moving a slider, although I'm still trying to profile the speed accurately.

Run simulation synchronously

---

src/code/stores/graph-store.coffee
src/code/views/graph-view.coffee
src/code/views/node-view.coffee
test/node-list-test.coffee

This adds "model descriptions," which are easily-comparable reductions of the model state to help decide when to redraw jsPlumb, or rerun the model.
By not redrawing jsPlumb everytime we run a simulation step, we improve our running speed significantly.
https://www.pivotaltracker.com/story/show/134467689

Use diffing to decide when to draw jsPlumb, run simulation. Speed up model.

---

src/code/models/codap-connect.coffee
src/code/stores/graph-store.coffee
src/code/stores/simulation-store.coffee
src/code/utils/lang/us-en.coffee
src/code/views/experiment-panel-view.coffee
src/code/views/experiment-view.coffee
src/code/views/simulation-run-panel-view.coffee
src/stylus/components/document-actions-view.styl
src/stylus/components/experiment-panel-view.styl
src/stylus/components/simulation-run-panel.styl
test/simulation-test.coffee

Adds a button and counter at the top of the simulation panel that lets a student specify the start of a new experiment.
[PT story for expiriments](https://www.pivotaltracker.com/story/show/134408545)
[PT story for not creating cases until record pushed](https://www.pivotaltracker.com/story/show/135145637)
@sfentress I think this is ready for a review if you get a chance.

Explicit experiment button

---

src/stylus/components/node.styl
src/stylus/components/top-node-palette.styl

Just 2 small changes:
- set line's z-index to 0,
- render palette on the top (z-axis = 3)

Tweak z-indexes to render component correctly

---

src/code/utils/open-clipart.coffee
src/code/views/image-search-dialog-view.coffee

These commits improve the search results list.
- images already used are hidden in the search results,
- internal images are hidden when searching was started

Internal library images clean up

---

src/code/stores/graph-store.coffee

With multiple selection enabled, we might update several nodes at once, depending on the selection.
This fix addresses a bug introduced with multiple selection where a node could not be converted to a collector.

Multiple selection `node.normalizeValues` bugfix.

---

src/code/models/codap-connect.coffee
src/code/utils/colors.coffee
src/code/utils/importer.coffee
src/code/utils/lang/us-en.coffee
src/code/views/graph-view.coffee

This PR aggregates a number of small bug fixes that mainly relate to CODAP interface:
* [#141349005] Fix bug: Step numbers do not reset between experiments
* [#141349005] Fix bug: Graph button does not open a graph in CODAP
* [##137553679] Increment experiment counter each time Sage loads
* [#135860017] Change color of mini-graphs (when not sending data) and filled part of bars to a darker gray
* (No PT Story) Fix missing 'this' binding in a setTimeout managing the CODAP request queue. (There were occasional console log errors due to this issue, mainly during the period that CODAP constructs a new case table component. Believe that data loss could occur from the exception thrown.)
* [#142411089] Fixed bug: Sage sometimes creates two "Sage Simulation" data sets on startup

Fix several codap related issues

---

src/code/utils/js-plumb-diagram-toolkit.coffee
src/code/views/graph-view.coffee

Previously the code was using the currently selected link when the blur handler on the link input was invoked due to a click outside of the link input.  However, the click would cause the currently selected link to be set to null before the blur handler was called causing the link not to be updated.
The code now adds the link to the closure that sets up the editing overlay so that it is available when the blur event is invoked.

Fixed clicking outside of link label editor losing change [#141320637]

---

src/code/views/graph-view.coffee

Simple change: the graph store just needed to listen for the relationshipSymbols setting in the state to change.  That setting is changed in `app-settings-store`.

Fix relationship symbols no longer come up [#136989689]

---

src/code/views/graph-view.coffee

When using sage.html outside of CODAP the links where not being drawn at startup if a file was loaded via the command line like this: sage.html#file=localStorage:node%20test
This change forces the graph to draw when it is mounted.

Fixed missing initial link drawing when loading a saved file [#142963961]

---

src/code/models/codap-connect.coffee

This change sends experiment numbers as categorical values instead of numeric values so when experiment numbers are added as a legend in a graph, then the legend is categorical instead of numerical.

Send experiment number as categorical to CODAP [#136990473]

---

src/code/stores/graph-store.coffee
src/code/stores/inspector-panel-store.coffee
src/code/views/graph-view.coffee
src/code/views/inspector-panel-view.coffee
src/code/views/node-view.coffee
src/code/views/relation-inspector-view.coffee
src/code/views/tabbed-panel-view.coffee

This removes the existing double click handler which was not being called anything this the link had a click handler.  Double clicking is detected with a simple test for two clicks within 250ms.
To enable the inspector panel to be commanded to open a panel its state was moved into a new store.

Double-click on link should now brings up relationship panel [#142637503]

---

src/code/stores/simulation-store.coffee
src/code/utils/time-units.coffee
src/code/views/node-value-inspector-view.coffee

NOTE: The default quantity is still set at 50.  There was no mention in the story if that was to be changed so I left it alone.
To update the default quantity change this line: https://github.com/concord-consortium/building-models/blob/481f0579c63331c089dd08bda53dd56d19a1be6e/src/code/stores/simulation-store.coffee#L39

Changed default recording unit to be days [#135136847]

---

src/code/views/link-relation-view.coffee

Changed from onBlur to onChange handler because when you click on the canvas the textarea is removed before the blur handler can get the value.

Fixed because text not always saving [#143497999]

---

src/code/models/codap-connect.coffee
src/code/stores/graph-store.coffee
src/code/stores/undo-redo-ui-store.coffee
src/code/utils/undo-redo.coffee
src/code/views/document-actions-view.coffee
src/code/views/global-nav-view.coffee

This change disables sending any events to CODAP about undo/redo when we are in standalone mode and instead relies on the Sage undo/redo manager to handle the requsests.
Before this change when standalone mode was detected the Sage undo/redo actions would be skipped and instead CODAP would be informed of the need for undo/redo. However this effectivly disabled the undo/redo buttons showing in Sage.
A new graph-store variable that tracks if we are running in CODAP (set via codap-connect) is now used to flag when undo/redo events should be sent to CODAP.
NOTE: there needs to be work done in CODAP in the DI API so that CODAP can notify the DI the state of the undo/redo stack.

Fixed undo/redo buttons so they work in standalone mode [#133193161]

---

src/code/models/node.coffee
src/code/stores/graph-store.coffee
src/code/views/node-view.coffee
src/stylus/components/node.styl

Adds a check when either a file is loaded or when a title is edited to require both a unique node name and the non-default node name ("Untitled"). If the name is not unique a number is appended to it starting at either 2 if the existing node name does not end with an integer or the ending integer + 1.
For visual feedback during title editing the input turns red when the name is not unique.

Nodes must have unique names [#134798657]

---

src/code/models/codap-connect.coffee

Enable the `numberToggle` UI on graphs created by Sage.
Requires CODAP PR [Enable graph numberToggle via plugin API](https://github.com/concord-consortium/codap/pull/148).

Enable `numberToggle` on graphs [#143266621]

---

src/code/models/codap-connect.coffee
src/code/models/node.coffee
src/code/stores/graph-store.coffee
src/code/utils/escape-reg-ex.coffee
src/code/views/node-view.coffee

- synchronize nodes/attribute IDs and titles/names at initialization time
- serialize synchronized IDs and names/titles for continued synchronization
- call plugin API updateAttributes when node titles are changed [#134408929]
- respond to plugin API updateAttributes notification by changing node title when appropriate [#137900155]
Requires CODAP PR [#151](https://github.com/concord-consortium/codap/pull/151) to provide the necessary changes to the CODAP plugin API. Requires CODAP PR [#152](https://github.com/concord-consortium/codap/pull/152) to support undo/redo of title changes when synchronizing CODAP attribute names.

Synchronize Sage node title/CODAP attribute name changes

---

gulp/tasks/default.js

Inspired by [GeniBlocks PR #97](https://github.com/concord-consortium/geniblocks/pull/97).
Gulp.watch has a known bug in which relative paths that begin with `./` cause added/deleted files to be ignored. The solution is to remove the leading `./` from relative paths and then pass `{ cwd: './' }` in the options to gulp.watch(). In the GeniBlocks PR this was as simple as removing the `./` from paths in `config.js`. Unfortunately, the same approach here led to build errors -- apparently other parts of the build process require the leading `./` -- and so the solution here is to programmatically remove the `./` from paths before passing them to gulp.watch().

Fix gulp.watch configuration so new/deleted files trigger rebuild

---

src/code/views/graph-view.coffee
src/code/views/node-view.coffee

When dropping a node in the canvas, the node image ends up offset (by 12 pixels) relative to the location of the image when dropped. This is particularly annoying when trying to align nodes.

Fix offset when dropping node onto canvas [#144136581]

---

src/code/models/codap-connect.coffee

- When showing case table, only show Sage table rather than all case tables. Specify `dataContext` in API call to create case table [#142390951]
- Sage-created graphs are no longer blank if there are multiple data contexts in the document. Specify `dataContext` in API call to create graph [#143413567]
- Use instance properties rather than constants for data context and collection names

Sage-created case tables/graphs work properly in documents with multiple data contexts

---

src/code/views/tabbed-panel-view.coffee

Fix bug in which no tab would be selected when switching node relation inspectors [#131890381]
- the TabbedPanelView was not always updating the state to the correct selected tab

Fix bug in which no tab would be selected when switching node relation inspectors

---

src/code/utils/js-plumb-diagram-toolkit.coffee

Changes jsplumb connection defaults so it does not use the bottom for a connection point.

Set the arrows not to link to the bottom [#141351881]

---

src/code/views/image-picker-view.coffee
src/code/views/image-search-dialog-view.coffee
src/code/views/tabbed-panel-view.coffee

- changed ImagePicker to use index for key intead of id to make it unique
- fixed @setState on unmounted component in ImageSearchResult
- fixed unselected tab when selecting image from search result [#144495595]
The last bug was introduced in this PR: https://github.com/concord-consortium/building-models/pull/273/

Fixed 3 bugs seen in search during unrelated PR review

---

src/code/models/node.coffee
src/code/views/node-view.coffee
src/code/views/stacked-image-view.coffee

- Collectors use a set of five images "randomly" distributed within the node [#144045227]
- in fact the images are in five fixed locations with small random perturbations so that they generally cover the view
Went through several iterations with Dan before settling on this behavior.

Collector shows multiple images of the assigned icon [#144045227]

---

src/code/views/relation-inspector-view.coffee
src/code/views/tabbed-panel-view.coffee

The `selectedTab` as understood by the TabbedPanelView was getting out of sync with the InspectorPanelStore's notion of the `selectedLink`. The fix implemented here is to configure the TabbedPanelView with an onTabSelected prop which is used to update the `selectedLink`, which eventually propagates back to set the `selectedTab` of the TabbedPanelView.
Note that two recent PRs (#273 & #275) dealt with the TabbedPanelView's setting of its `selectedTab` state. Given that the InspectorPanelStore's `selectedLink` is used to specify the `selectedTab` prop for the TabbedPanelView, it's worth revisiting those fixes to make sure that they're still appropriate in light of these changes.

Fix relationship panel tab navigation bug [#144497757]

---

src/code/views/node-view.coffee

If the edit were completed with a click outside the edit field rather than the enter/return key, the undo/redo mechanism would not be invoked. The bug occurs when the `onBlur` event is not handled because the `input` element is destroyed too early. The fix here is to always render the `input` element but control its visibility with `display: none`, so the underlying DOM element doesn't get destroyed and the `onBlur` event gets handled correctly.

Fix undo/redo of node title changes without enter key [#106772348]

---

src/code/mixins/node-title.coffee
src/code/views/node-view.coffee

Fix bug when editing title after undoing title change [#145244601] 
Trim node titles to eliminate leading/trailing white space [#144377505]
A recent bug-fix made the <input> DOM element persistent. This also made its contents persistent, which allowed the incorrect contents to be retrieved because the <input> element is uncontrolled. But since we have an onChange handler, we simply make the <input> element controlled at this point.

Fix bug when editing title after undoing title change [#145244601]

---

src/assets/index.html
src/assets/sage.html

- fix bug in which a URL like "http://sage.concord.org/?lang=zh" will reload the page infinitely adding "sage.html" to the URL each time
- preserve query parameters when redirecting
- pass query parameters through CFM to embedded app
- fix typo "SageCloundFileManager" -> "SageCloudFileManager"
@knowuh I'm assigning this one to you for review since you seem to have written some of the code being modified here (and I've been hitting up Doug pretty hard lately).

Improve Sage URL query parameter handling

---

src/code/views/node-view.coffee

Only "ensure" unique node names upon completion of user edit [#145949051]
- don't try to replace what the user is typing while he/she is typing it

Only "ensure" unique node names upon completion of user edit

---

src/code/views/modal-google-save-view.coffee
src/code/views/node-value-inspector-view.coffee
src/code/views/simulation-inspector-view.coffee
src/stylus/app.styl
src/stylus/components/simulation-panel.styl
src/stylus/mixins/default.styl

Make checkbox labels clickable [#144866291]. Fix a couple of CSS hygiene issues:
Fix Stylus `absolute` function
- `'auto'` is an invalid value; use `auto` instead
- eliminate `width` & `height` as they were never used (and aren't involved in absolute positioning)
Fix `marging` -> `margin`
@knowuh There will be a conflict with the `flow-ui-changes` branch so you can let me do the merge.

Clickable checkbox labels; CSS hygiene

---

src/code/models/simulation.coffee

From: Daniel Damelin <ddamelin@concord.org>
Subject: problematic thing with algorithm
Date: May 26, 2017 at 9:04:42 AM PDT
To: Kirk Swenson <kswenson@concord.org>, Steve Roderick <steveroderick@mac.com>
HI Kirk and Steve,
Take a look at this model:
https://codap.concord.org/releases/latest/static/dg/en/cert/index.html#shared=20882
For the simple flow we divide by 100, but for the one directly added to “b” we don’t so that aspect of the adding overwhelms the value of “b” making the flow from “a” to “b” mostly irrelevant.
Not sure what to do here. I think our current rule is that as long as there is nothing pointing to the source collector “a” we divide the flow value by 100, but we might be able to fix this by also saying we only divide the flow value by 100 if both the source “a” and sink …

Don't divide flow by 100 if target of flow has other inputs [#146168951]

---

src/code/models/simulation.coffee
src/code/stores/graph-store.coffee
src/code/stores/simulation-store.coffee
src/code/views/node-svg-graph-view.coffee
test/simulation-test.coffee

- fix one-step recording bug (should only record one data point)
- fix mini-graphs bug in which the first point(s) weren't plotted [#146030015]
- fix bug in which cached mini-graph data could grow unbounded [#146183765]
- adjust simulation unit tests to test initial values
One of the changes I made to the simulation loop while making the recent set of improvements to support flow nodes and collectors better was to add one step to the simulation loop to account for the initial conditions, i.e. if the user asks for ten steps, eleven data points should be generated -- the initial conditions plus the results of the first ten steps. This made sense in that context, but had some less-than-desirable results in other contexts, notably that one-step recording would now record two steps and …

Synchronize use of duration throughout system

---

src/code/models/node.coffee

Regular nodes in closed loops with collectors should not have sliders [#145981913]
- extends existing closed loop detection mechanism to check for collectors in the closed loop

Regular nodes in closed loops with collectors should not have sliders

---

src/code/utils/js-plumb-diagram-toolkit.coffee
src/code/views/graph-view.coffee

- flow links attach to the flow node at the locations of the "pipes" in the image
- transfer-modifier links attach to the flow node above the flow links
- range links attach to the flow node on the top and bottom or on the sides away from the flow and transfer-modifier links
- all links are adjusted to touch the node rather than stopping ~10-15 pixels away at the node surround
To accomplish these things we abandon jsPlumb's "Continuous" anchors, for which jsPlumb assigns the connection points and adjusts them on the basis of how many connections there are, etc., in favor of a "Dynamic" (in jsPlumb lingo) set of "Static" (also jsPlumb lingo) anchor points chosen not to interfere with each other.
@dstrawberrygirl I know you're away at a conference at the moment, but you've done some work in …

Improve locations of connections to flow nodes

---

src/code/models/simulation.coffee
src/code/stores/simulation-store.coffee
test/simulation-test.coffee

From discussion on https://www.pivotaltracker.com/story/show/145575739 and Slack:
Evangeline Ireland
[2:46 PM] 
So based on this story: https://www.pivotaltracker.com/story/show/145575739
Only runs that have collectors should have steps that start at 0. Models with no collectors should still start at 1? Current production all models start at 0.
Dan Damelin [4:07 PM] 
Yeah. I think it should start with 1 for non collectors.

Steps start at 1 for models without collectors [#146744415]

---

src/code/models/node.coffee

`Node.outLinks()` accepts `relationType` argument like `Node.inLinks()`
- fixes [#147461367] which was treating outbound `accumulator` links as `transfer` links due to the expectation that the `relationType` argument would be respected.
@dougmartin If you could take a look at #309 as well I'd like to get both of them into a build. Thx

Collector nodes should ignore outbound `accumulator` links

---

.travis.yml
package.json
src/code/views/svg-graph-view.coffee
yarn.lock

@knowuh Could you take a look?
Previously, when drawing the "Varies" relationship graph, when your mouse left the graph area you'd lose connection, and you'd have to re-click the graph to continue drawing.
Now you should be able to leave the graph and return to it and continue drawing. Further, if you move above or below the graph, it should continue drawing at the very top or bottom. It should not edit points if the mouse is to the left or right of the graph.
It can be tested here: https://sage.concord.org/branch/relation-graph-mouse-handler/sage.html

Update relation graph drawing behavior

---

package.json
src/code/data/migrations/20_add_complexity.coffee
src/code/data/migrations/migrations.coffee
src/code/models/relation-factory.coffee
src/code/stores/app-settings-store.coffee
src/code/stores/graph-store.coffee
src/code/stores/simulation-store.coffee
src/code/utils/lang/en-US.coffee
src/code/views/app-view.coffee
src/code/views/graph-view.coffee
src/code/views/link-relation-view.coffee
src/code/views/node-value-inspector-view.coffee
src/code/views/simulation-inspector-view.coffee
src/stylus/components/simulation-panel.styl
test/complexity-test.coffee
test/loading-serialization-test.coffee
test/migrations-test.coffee
yarn.lock

Hi @knowuh, this is a bigger PR. If you could look at it any time in the next few days that would be great.
This adds more settings for the "complexity" of a diagram, beyond the original "diagram-only tools" checkbox that existed before.
You can now set the complexity to four levels, "diagram-only", "basic relations", "expanded relations" and "collectors." By default a model starts at "basic", unless (1) it loads data that had the old `diagramOnly: true` setting, or (2) you launch with the hash param `#simplified=true` (matching the old feature).
Lower complexity levels prevent the user from accessing certain tools, like the "varies" relationship, all the scalar relationships, and turning nodes into collectors.
The graph is scanned to note the minimum complexity it supports, and prevents …

Complexity levels

---

src/code/models/relation-factory.coffee
src/code/models/simulation.coffee
src/code/stores/graph-store.coffee
src/code/utils/lang/en-US-master.json
src/code/utils/lang/en-US.json
src/code/views/graph-view.coffee
src/code/views/link-relation-view.coffee
src/stylus/components/relation-inspector.styl
test/simulation-test.coffee

@kswenson since you were most recently working in the simulation code, I wonder if you could take a look at this.
This implements this story: https://www.pivotaltracker.com/story/show/151201810
Non-collector variables can link to collectors with a new relationship type, "set initial value." The model should run exactly the same as if the collector's own initial value had been set by hand.
The simulation changes ended up being pretty simple once I realized I should just set the initial values before running through the steps.
The model can be run here: http://sage.concord.org/branch/set-collector-init-value/sage.html
In CODAP: http://codap.concord.org/releases/latest/static/dg/en/cert/index.html?di=http://sage.concord.org/branch/set-collector-init-value/sage.html
(en-US-master.json …

Set collector initial value

---

src/code/models/node.coffee
src/code/models/relation-factory.coffee
src/code/stores/simulation-store.coffee
src/code/utils/lang/en-US-master.json
src/code/utils/lang/en-US.json
src/code/utils/link-colors.coffee
src/code/views/graph-view.coffee
src/code/views/link-relation-view.coffee
src/stylus/components/inspector-panel.styl
test/simulation-test.coffee

This PR changes the way a source (and now a target) node can change their flow relationship.
The goal is to reduce the number of flow modifiers and allow both the source and target nodes to modify the flow.
* There are now just two flow-modifiers: proportional and inverse proportional flow.
* Target nodes can now affect the flow.
There have been modifications to the text and language files.  The text has to change significantly when the target node is changing the flow.
Also as part of this PR, the default MAX for collectors is 1000, and the default simulation length is 20 steps.  These changes were made so that the effect of flow-modifiers could be easily seen using system defaults in the mini-graphs.
Tests which that involved the MAX of collectors or the formulas for flow-modifications …

Changes to flow-modifying links.

---

src/code/models/node.coffee
src/code/models/simulation.coffee
src/code/models/transfer.coffee
src/code/stores/graph-store.coffee
src/code/stores/simulation-store.coffee
src/code/views/node-value-inspector-view.coffee
src/code/views/simulation-run-panel-view.coffee
src/stylus/components/value-inspector.styl
test/simulation-test.coffee

@sfentress would you mind looking at this PR?  
It's smaller than the last, and related. Hopefully, it's a quick read.
Summary of Changes:
* The calculation for a flow by default should use `limiting factor` (aka `product`)
* Simulation reruns when the transfer's `combine method` is changed, so graphs update.
* Remove a special case of dividing a collectors value by 100 if there is no input. (This is the one you and Dan were discussing in the last PR)
* Immediately enable `display mini-graphs` if we are running a simulation with collectors. 
Some tests needed to be adjusted to handle the divide by 100 change.
Related PT Stories:
https://www.pivotaltracker.com/story/show/153639811
https://www.pivotaltracker.com/story/show/153639752
https://www.pivotaltracker.com/story/show/154029978 …

Several small collector / flow adjustments

---

src/code/models/codap-connect.coffee

CODAP will soon be adjusting the default setting for preventBringToFront
from true to false. This goes along with other changes intended to make
plugins behave more like other components in the CODAP workspace. Sage
relies on being placed in the background, especially in standalone mode,
so we initialize with the property, instead of relying on the default.

[#155049999] Set CODAP property: preventBringToFront

---

src/code/stores/graph-store.coffee
src/code/views/node-view.coffee
src/code/views/simulation-inspector-view.coffee

Double-clicking a link shouldn't open the relationship window, neither should double-clicking a node when we're in that mode. This fix blocks those actions specifically, while leaving the menu functionality intact to enable the user to change to a different mode if they wish.

Stop UI elements appearing in Diagram-Only mode

---

src/code/data/migrations/23_add_simulation_type.coffee
src/code/utils/importer.coffee

This patch addresses checking for evidence of collectors in older models - all static equilibrium models would include the default "include collectors" checkbox and, at import, would be read incorrectly to newer builds as dynamic simulations. This should hopefully address the problem at import while not changing models saved on current versions.

Migration import fixes

---

test/codap-helper.coffee
test/complexity-test.coffee
test/loading-serialization-test.coffee
test/migrations-test.coffee
test/node-list-test.coffee
test/node-test.coffee
test/simulation-test.coffee

The mocha tests for building models weren't  running for about 4 months, because of a `describe.only` stanza that was accidentally left in place …
So this PR fixes that, and also cleans up some CodapConnect stubbing that was happening.
The changes are not actually as extensive as they look, but because of the how git-diffing worked in this instance, it seems like there are a lot of changes.
The main thing is that lots of ` @sandbox.stub CodapConnect, "instance", ->`  were replaced with a helper method `CodapHelper.Stub()`  (and `CodapHelper.UnStub()` ).   
This helper was extracted because as we start expecting more messages to be sent to CodapConnect, 
(such as `_createMissingDataAttributes` it would be nice to only add them once.
@kswenson I have been bugging @dstrawberrygirl for many …

159348401 fix tests not running

---

src/code/stores/graph-store.coffee
test/node-list-test.coffee

This had stopped working, because we used to save `combineMethod` as a property on flow links. Flow links are no longer a thing, so now we store this as a property on the Nodes.  We have to add `combineMethod` to the serialization hash, so that the graphView knows when it needs to re-run the simulation.
Story:
Graphs should update when Combine Variables Using menu changes.
[#154029978]
https://www.pivotaltracker.com/story/show/154029978

Graphs should update when Combine Variables Using menu changes.

---

test/loading-serialization-test.coffee

I started working on [this bug](https://www.pivotaltracker.com/story/show/154706564) -- but could not reproduce it.  
The bug states that node `combineMethod` ("Combine Variables Using" in the link inspector) wasn't being saved correctly.  
I smoked tested it, and verified that the value was being stored for both flows, and non-flow connections. (The story seemed to indicate that this might be an issue with flow / transfer links only).
I assume that this bug was fixed in prior work.
This commit is for two tests that verify that the node `combineMethod` of nodes is being stored correctly, and confirms that the value is serialized.
Story:
"Setting for combining variables is not being saved or restored properly."
[#154706564]
https://www.pivotaltracker.com/story/show/154706564

Tests: to verify upstream fix for `combineMethod` not being serialized.

---

src/code/mixins/app-view.coffee
src/code/stores/app-settings-store.coffee
src/code/views/app-view.coffee
src/code/views/document-actions-view.coffee
src/code/views/graph-view.coffee
src/code/views/inspector-panel-view.coffee
src/code/views/node-view.coffee
src/code/views/node-well-view.coffee
src/stylus/app.styl
src/stylus/components/global-nav.styl
src/stylus/components/inspector-panel.styl
src/stylus/components/link-view.styl
src/stylus/components/top-node-palette.styl

For the DAT-Cross project:
- Added `lockdown` url hash parameter to limit the ability of users to delete nodes. lockdown=true means users can only remove relationships, not nodes themselves. The assumption is that these users will have models loaded on initialization and will not need a node palette.
- Added `hide` url hash parameter that can remove any of the following pieces from the layout:
```
globalNav
actionBar
inspectorPanel
nodePalette
```
Additional style settings have been added to ensure a viable layout when any of these elements are removed from the UI. In most cases, `display:none` is sufficient to visibly remove them without significant code rework to handle them not being present.
- Added `delete` button to the action bar next to `undo/redo` buttons. This only appears if …

DAT-Cross UI changes

---

src/code/models/codap-connect.coffee

Original work didn't account for new documents loading without having run a simulation at least once.
Story:
Experiment increment doesn't work in translated versions of SageModeler/CODAP
[#159214059]
https://www.pivotaltracker.com/story/show/159214059

Fix: Exp number incremen on master. Sage/CODAP

---

src/code/models/graph-primitive.coffee
src/code/stores/graph-store.coffee
src/code/utils/importer.coffee
test/node-list-test.coffee

Fixes a bug where new nodes sometimes could not be dropped because the node id already existed in the loaded file.
This change sets the counters used in the nextID generation to be the max  + 1 of each node type.

Fixed nextID generation after file is loaded [#160661756]

---

src/code/views/palette-add-view.tsx

This bug was introduced in the decaf process  An if was added to check if the callback existed what wasn't in the coffeescript.

Fixed new image button click does not do anything [#161817892]

---

src/code/models/node.ts
src/code/models/transfer.ts

Missed setting the `isTransfer` and `combineMethod` variables in decaf conversion.
CoffeeScript code was: 
```
Node = require './node'
tr = require "../utils/translate"
DEFAULT_COMBINE_METHOD='product'
module.exports = class Transfer extends Node
type: 'Transfer'
isTransfer: true
combineMethod: DEFAULT_COMBINE_METHOD
setTransferLink: (link) ->
@transferLink = link
@title = @computeTitle()
computeTitle: ->
if @transferLink
tr '~TRANSFER_NODE.TITLE', { sourceTitle: @transferLink.sourceNode.title, \
targetTitle: @transferLink.targetNode.title }
else
undefined
```

Fixed valve icon not coming up [#161824729] and transfer Relationships are lost on restore [#161828639]

---

package.json
src/code/mixins/components.ts
src/code/mixins/draggable.ts
src/code/mixins/image-dialog-view.tsx
src/code/views/app-view.tsx
src/code/views/document-actions-view.tsx
src/code/views/experiment-panel-view.tsx
src/code/views/global-nav-view.tsx
src/code/views/graph-view.tsx
src/code/views/image-browser-view.tsx
src/code/views/image-link-dialog-view.tsx
src/code/views/image-my-computer-dialog-view.tsx
src/code/views/image-picker-view.tsx
src/code/views/image-search-dialog-view.tsx
src/code/views/inspector-panel-view.tsx
src/code/views/link-relation-view.tsx
src/code/views/modal-palette-delete-view.tsx
src/code/views/node-inspector-view.tsx
src/code/views/node-svg-graph-view.tsx
src/code/views/node-value-inspector-view.tsx
src/code/views/node-view.tsx
src/code/views/node-well-view.tsx
src/code/views/palette-add-view.tsx
src/code/views/palette-inspector-view.tsx
src/code/views/relation-inspector-view.tsx
src/code/views/simulation-inspector-view.tsx
src/code/views/simulation-run-panel-view.tsx

1. Fixes some trivial errors related to incorrect `this` binding.
2. Previous Mixin implementation was unable to receive new `props`. I've fixed. Mixins no longer extend React.Component. Instead, they just implement their own `IMixin` interface that resembles React.Component. I think it should be a bit cleaner, as there's no need for mixin to be a "real" React Component.
That seems to fix all the errors related to image search/upload dialog.

Fix image upload, fix and refactor Mixin implementation

---

src/code/data/migrations/26_remove_minigraphs_visibility.ts
src/code/data/migrations/migrations.ts
src/code/models/node.ts
src/code/stores/app-settings-store.ts
src/code/views/graph-view.tsx
src/code/views/node-view.tsx
src/code/views/simulation-inspector-view.tsx
src/code/views/simulation-run-panel-view.tsx
test/loading-serialization-test.ts
test/migrations-test.ts

This PR implements UI changes requested in https://www.pivotaltracker.com/story/show/162022659.
Also, there's quite significant change to migration testing. IMHO it didn't work too well before.
1. Migration change data object in place. But the test data wasn't cloned. It didn't make much sense.
2. Migration tests were always running all the migrations, up to the most recent version. It was causing that old migration tests had to be deleted if the new migration was touching the same data. E.g. my recent removal of mini-graph setting was affecting initial mini-graph setting migration. I've changed tests to run migrations only to a given point, so migrations can be correctly tested and we don't have to remove any old tests.
3. Also, I've restored some commented out migration tests, as now …

Simplify mini-graphs viewing, refactor migration tests, restore commented out migration tests

---

src/assets/css/splash-screen.css
src/assets/js/splash-screen.js
src/templates/index.html.ejs

[#162022115]
I've moved HTML generation to JS file. Now we can reuse in Sage Modeler standalone site. Also, I've slightly reordered JS loading. That way splash screen shows almost immediately when the big JS files are still loading. I've tested that using Chrome network throttling.

Reimplement splash screen, make it reusable, reorder JS loading

---

src/code/models/codap-connect.ts
src/code/stores/graph-store.ts

The main reason why we couldn't undo node add when Sage was embedded in CODAP was the fact that Sage was creating a new attribute in CODAP. This action makes CODAP document dirty and resets undo stack. When we pass `{ dirtyDocument: false }` metadata, CODAP won't mark document dirty and won't reset undo stack.
This whole undo logic is a bit questionable for me, but it works like that in other places (e.g. when we change a node). So, I'm just following an existing pattern.
There's a second part of this PR. What should we do about CODAP attribute when we undo node add and we have to remove this node?
Regular node remove action doesn't delete CODAP attribute. It makes some sense, as there might be some interesting data already. However, in the case of immediate undo action, I think it makes …

Let users undo node adding when Sage is embedded in CODAP

---

src/code/stores/graph-store.ts

[#161790553]
Failing test case:
- open CODAP table
- add two nodes
- click undo twice -> it works, both nodes and CODAP variables disappear
- click redo twice -> it works, both nodes and CODAP variables re-appear
- click undo -> it fails, node disappears, but CODAP variable stays there
That was caused because codapID and codapName were not getting updated.

Another fix to node add undo action

---

src/code/models/codap-connect.ts

This depends on CODAP PR https://github.com/concord-consortium/codap/pull/263 to work.
But nothing prevents us from merging this in, it won't break anything. Actually, the `position` parameter is documented in CODAP API, so it should be supported anyway.

Show CODAP text box and table at the bottom

---

src/code/views/node-view.tsx

This is related to Dan's comment here:
https://www.pivotaltracker.com/story/show/162022659/comments/196975446
Previously, I misunderstood one of the points in this story.
We won't show sliders without handle that were acting as a kind of a tiny bar graph. It's redundant now, as we always see a mini-graph when it's available.

Fix logic related to sliders, dont show them when it's not necessary

---

src/stylus/components/svg-graph-view.styl

Here is the new centered label position:

Fixed vary draw relationship label location [#162461761]

---

src/code/views/node-view.tsx

IE/Edge only allow text or URL as the data types.

Fixed invalid argument error for dataTransfer.setData [#164460118]

---

src/code/views/value-slider-view.tsx

NOTE: this bug only occurs on Mobile Safari

Fixed null is not an object on svg slider [#164496936]

---

src/code/views/graph-view.tsx

The graph link click handler was being called when the link label input was selected causing an error to throw because the clicked item was not a link.

Fixed error thrown when selecting label input [#164435260]

---

src/code/views/inspector-panel-view.tsx

The inspector panel now listens for selections and if they are cleared it closes itself to prevent a "flash" of the previouly opened panel when items are re-selected.

Fixed "flash" of inspector if previously opened [#164294887]

---

src/code/views/simulation-run-panel-view.tsx

As part of the work to add types to the generic dropdown view the unit attribute was removed from the simulation step dropdown which caused a translation error.

Fixed missing units attribute in simulation step dropdown [#164511759]

---

src/assets/sage.html

This should have been done months ago when I created the cloud-file-manager S3+CloudFront distribution.

Change CFM urls to use cloud-file-manager CloudFront urls

---

src/assets/sage.html
src/templates/index.html.ejs
src/templates/sagemodeler.html.ejs

Added <!DOCTYPE html> so that jQuery's window.height() function does not return 0 in Firefox (which caused the dialogs to not center vertically).

Fixed CFM dialog vertical centering in Firefox [#161082471]

---

src/code/stores/app-settings-store.ts
src/code/views/document-actions-view.tsx

Test link: https://sage.concord.org/branch/163402991-hide-buttons/sage.html?standalone=true

In "model diagram" mode hide table and graph buttons [#163402991]

---

src/code/utils/js-plumb-diagram-toolkit.ts

Test url: https://sage.concord.org/branch/164294896-fatten-link-target/sage.html

Restore "fatter" target for clicking on link [#164294896]

---

test/node-list-test.ts
test/simulation-test.ts

Some mocha tests have stateful dependencies.  Running 2x breaks tests.
The test suite runs fine the first time if run with `npm test`.
If however the suite is run with `npm run test -- --watch`
subsequent runs will fail because the simulation retains (and mutates)
state related to the number of simulation steps.
The fix is to explicitly set default simulation parameters in test blocks for:
* expirimentFrameNumber
* duration
* capNodeValues
[#164835954]
https://www.pivotaltracker.com/story/show/164835954

Fixes 🐞 stateful dependencies in mocha tests.

---

src/code/utils/topology-tagger.ts
test/topology-tagger-test.ts

[NP/DL] PR to implement the counting of "collector" nodes as part of PT [SageModeler generates counts of model components](
https://www.pivotaltracker.com/story/show/164634326) as relates to the counting of the number of collector nodes in the model.
Also includes a little "name" adjustment to the tag fields that are include so they are more parallel and closer match the names described in the PT story.
Please note that the cycle detection is only part of the implementation of the the "feedback" detection described in another PT story [SageModeler generates a tag for feedback loops](https://www.pivotaltracker.com/story/show/164634579). This second story is not yet complete.

Counting collectors, unit tests, renamed tags

---

src/code/views/graph-view.tsx

This fixes an issue where a link dragged to a transfer node will cause the transfer nonde to lose drag focus.

Reverse order of target/link drawing [#164832960]

---

src/code/views/graph-view.tsx

From PT Story:
> Click on a link to select it. Then click again to bring up link editing dialog.
> Add some text, then click outside that text box and the text you typed is gone.
> It stays if you hit return, but I think many will not hit return.  (safari only)
> Also, once you do have label text there you can no longer click on the text to edit it. You used to be able to.
In Safari, if you are in the middle of editing a label on a link, then click on the background of the graph,
the link label change is lost.  The `onChange` event in `js-plumb-diagram-toolkit.ts` (Line 242) never fires.
I tried adding `blur` and `focusout` handlers to the input.  But none of those events are triggered when the user clicks on the
background of the graph, the reason is that the setState is called, changing …

Fix: Safari Link Editing values not saved when focus lost.

---

src/code/views/graph-view.tsx

Fixes a bug that was introduced when a timeout was added in the graph mousedown handler.

Fix graph selection box in Safari [#164438776]

---

src/code/views/node-view.tsx
src/stylus/components/node.styl

Addresses [#162094889] to make the white area behind a selected node draggable, not just the node image itself. Implemented a solution involving a temporary extra div that is the same size as the node while the node is selected, raised the link button up a notch on z-index to ensure that functionality was not altered while the selected mode was in effect.

Make the white area of a selected node draggable

---

src/stylus/components/node.styl

Removes css added in commit b3c9036523a0fd8135ab1318c2433f0b8cd20f8a.  This was causing the arrow position calculations that js-plumb does to be off.

Removed updated style for node-title-box which caused arrows to be positioned incorrectly

---

src/code/models/codap-connect.ts
src/code/stores/graph-store.ts

The latest CODAP is faster at returning messages after connecting and we've found a race condition between the undoRedoManager becoming available and the returned messages causing methods to be called on the undoRedoManager.  This PR waits for the graph store to become available (ie the undoRedoManager is inited) before talking to CODAP.

Add wait for graphstore before connecting to CODAP

---

src/code/models/selection-manager.ts

Removed selection notification in SelectionManager._clearSelection and insured correct _clearSelection/clearSelection calls are made so that notification is performed only once.
Previously when a node was selected when another was selected the selection was cleared and notifications were sent before the new node was selected causing the inspector panel to close itself.

Fixed clearing node/link selection [#168140645]

---

src/code/utils/lang/el.json
src/code/utils/lang/en-US-master.json
src/code/utils/lang/en-US.json
src/code/utils/lang/es.json
src/code/utils/lang/et.json
src/code/utils/lang/he.json
src/code/utils/lang/nb.json
src/code/utils/lang/nn.json
src/code/utils/lang/pl.json
src/code/utils/lang/tr.json
src/code/utils/lang/zh-TW.json
src/code/views/about-view.tsx
src/stylus/components/palette-inspector.styl

- Prevent dragging of "info" image on palette [#169639253]
- Change link to help under the "about" menu [#169481216]
- Change "about" text under button to "help." [#169481178]
NOTE: poeditor reordered some of the entries in the json files causing the diffs to be noisy.  The only real change should be for `~MENU.ABOUT`

Multiple ui updates (each in own tagged commit)

---

src/code/utils/drop-handler.ts
src/code/views/graph-view.tsx

Disables the componentType when importing csv data into CODAP so that csv import path can be followed.  Also adds a name value so CODAP can use it instead of the contents of the data-uri for the table name.

Fix csv drops into CODAP [#168381157]

---

src/stylus/components/node.styl

Adds a z-index to the graph button so that it is clickable when the node selection box is visible behind the node.

Fix graph button when node is selected [#170183697]

---

src/code/models/node.ts
src/code/models/simulation-v1.ts
src/code/models/simulation-v2.ts
src/code/stores/simulation-store.tsx
src/code/utils/url-params.ts
test/simulation-test.ts
test/simulation-v1-test.ts
test/simulation-v2-test.ts

This PR adds a new module called Simulation V2. It's partially based on previous Simulation class (which is still there but renamed to SimulationV1), although there are many changes:
1. No hacks with 10 pre-steps and 30 steps that average values (unless it's necessary, more about that below). Cleaner integration loop.
1. Static nodes are evaluated recursively and immediately. We used to treat them as a part of the integration loop, and each step included 10 "pre-steps" to push values down the chain. This didn't seem correct and was limiting chains of static relationships to 10 nodes, or there was some delay.
1. Loops that include only static nodes are now detected and evaluated only if necessary. A similar method is used -> 30 steps + averaging. But it's more explicit and not run all the …

Add Simulation V2 which provides RK4 integration method

---

src/code/stores/graph-store.ts
src/code/utils/topology-tagger.ts
test/serialized-test-data/topology-test-cases/two-transfer-nodes.ts
test/topology-tagger-test.ts

The topology tagger was dereferencing a transferNode attribute that was not being cleared when the transfer node was deleted in the graph store.
Along with this fix the graph store deleteNode method was updated to clear the  transferNode attribute on the link.

Fixed topology tagger breaking when transfer node is deleted [#170410042]

---

src/code/stores/image-dialog-store.ts
src/code/views/image-metadata-view.tsx
src/code/views/palette-inspector-view.tsx
src/stylus/components/image-metadata.styl
src/stylus/components/palette-inspector.styl
src/stylus/components/tabbed-panel.styl
src/stylus/components/top-node-palette.styl
test/image-dialog-store-test.ts

This
1. Fixes a bug where dragging the New Image node into the canvas and then changing tabs made the New Image Dialog close
2. Enlarges the panel containing the tabs, so more can be seen at once
3. Fixes the unclickable space right below the palette (https://www.pivotaltracker.com/story/show/172150136)
4. Made the image info box under the palette shorter (https://www.pivotaltracker.com/story/show/172150275)

Image collections improvements

---

package-lock.json
package.json
src/assets/img/fullscreen-exit.svg
src/assets/img/fullscreen.svg
src/code/app.tsx
src/code/stores/app-settings-store.ts
src/code/utils/scale-app.ts
src/code/utils/url-params.ts
src/code/views/app-view.tsx
src/code/views/fullscreen-button.tsx
src/stylus/components/fullscreen-button.styl
src/templates/lara.html.ejs

When Sage is embedded using the Document Store, a fullscreen button is provided for it, but otherwise it doesn't have one.
This adds a url parameter "fullscreenButton" that can provide a similar-looking fullscreen button.
https://www.pivotaltracker.com/story/show/172377261

Add optional fullscreen button (?fullscreenButton=true)

---

src/code/utils/js-plumb-diagram-toolkit.ts
src/code/utils/scale-app.ts
src/code/views/app-view.tsx
src/code/views/graph-view.tsx
src/code/views/node-view.tsx
src/vendor/jsPlumb.js

When using stand-alone Sage scaling, we have to handle all the mouse transformations ourselves. This wasn't an issue in the DocumentStore, because that scaled the entire iframe, which allows the mouse coordinates of the internal app to ignore scaling.
This is mostly straight-forward, dividing coordinates as needed by the current scale. The only annoying thing (which caused hours of face-desking) is how jsPlumb handles zooming. jsPlumb does have a `setZoom` function, which would in theory work, but each node has a drag-drop handler which doesn't hear the `zoom` event, because we call `reset` after the handler's listener is created. This hacks jsPlumb to use a single top-level zoom scale in this case.
No behavior should be different if scaling is 1 (which is always the case is …

Fix scaling of app

---

src/code/models/codap-connect.ts
src/code/utils/select-self.ts
src/code/views/app-view.tsx
src/code/views/graph-view.tsx

Sends CODAP a select message to select the app when any click is performed in the app.  This will unselect all other CODAP components which will also remove their window menus.  This is needed after the new text component added a large menu.
The click handler was added both to the main app view, attached to the window, and the graph view as the graph view uses jsPlumb which attaches its own click handler which prevents the outer window handler from being called.

Add select of app when embedded in CODAP [#173785724]

---

src/code/stores/graph-store.ts
src/code/utils/importer.ts

Adds a flag to skip undo/redo when importing nodes so that CODAP isn't notified of the load.  Without this flag CODAP thinks the document is getting dirtied at load time.

Fixed building-models side of dirtying document on load [#170849917]

---

src/code/models/codap-connect.ts

Changes preventDataContextReorg property of SageModeler plugin to be "false" so that tables can be reorganized, including those new tables that get created through the "new table" button.

Added preventDataContextReorg to CODAP plugin params [#170897787]

---

src/code/mixins/node-title.ts
src/code/models/transfer.ts
src/code/stores/graph-store.ts
src/code/views/node-view.tsx

- When a flow variable is created it still gets the same default name and this name is hidden.
- If the user hovers over or selects a flow variable, the name becomes visible _and_ editable.
- If the user edits the variable name, then this name is now shown even when the variable is not selected or hovered over. In other words, it behaves just like any other variable.
- If the user delete the customized name of the flow variable, it reverts to its default name and hidden behavior.

Added naming of flow [#171530932]

---

src/templates/lara.html.ejs

If a model has no authoredState, and the model is being used in runtime, LARA will pass in an initial state as 
```
{
...
authoredState: null
}
```
which is fine.
However, for some reason in report-mode, LARA passes the initial state as
```
{
...
authoredState: ""
}
```
which causes `JSON.parse` to throw an error. This adds a simple check on length which should fix that, and also protects it further with try/catch.
(This should also be fixed on LARA's end, but that's out of scope right now.)

Guard against LARA passing empty string

---

src/code/stores/graph-store.ts
src/code/utils/undo-redo.ts

This adds both the wrapping of a command batch around the slider start/end drag and a new setter method in the undoRedo manager to enable/disable further command batches.  This needed as each slider value change caused a seperate command batch to be created.
This also fixes a typo in the internal end command batch method.

Collapsed slider dragging actions into one undoable step [#171509259]

---

src/code/models/node.ts
test/simulation-v2-test.ts

This fix ensures that the initial value of the node lies within the min/max values of the node.
This bug manifested itself with a saved model that had initial values of two accumulators set at 100000000.  This caused the graphs to not draw correctly as the value was outside of the allowed range.

Fix broken mini-graphs/broken initialValue setting [#180624189]

---

src/code/views/node-view.tsx

Change double click on a node to select the first unset relationship, or if none, then select the first relationship.

The relationship panel should guide the user to set unselected relationships [#180450641]

---

src/code/models/codap-connect.ts
src/code/stores/app-settings-store.ts

At some point CODAP started deleting the samples subcollection when the data point column was deleted and the collection had no more attributes.
This fix moves the deleting of the extra column to after the simulation has run so that the collection remains when the column is removed.
This also adds code to re-create the missing subcollection on saved files.

Fix data export upon record [#180562893]

---

src/code/stores/graph-store.ts
src/code/utils/importer.ts
test/graph-store-test.ts

We used to use "New Model" as the default but this caused
hash(dataOnLoad) !== hash(dataOnSave) which then caused
immediate saves when a new model was loaded.  These
immediate saves caused the linked interactive UI to show
as it compares save times to figure out it content changed.
We opted to remove the default here instead of setting the
default in graphStore.init() so that old saved models, with
null as their filename, would hash the same.

Removed default "New Model" filename [#181175814]

---

src/code/models/node.ts
src/code/stores/palette-delete-dialog-store.ts
src/code/stores/palette-store.ts
src/code/utils/lang/en-US-master.json
src/code/utils/lang/en-US.json
src/code/views/app-view.tsx
src/code/views/image-picker-view.tsx
src/code/views/img-choice-view.tsx
src/code/views/inspector-panel-view.tsx
src/code/views/node-view.tsx
src/code/views/palette-delete-view.tsx
src/code/views/palette-inspector-view.tsx
src/code/views/quick-action-button.tsx
src/code/views/quick-action-menu.tsx
src/stylus/components/node.styl
src/stylus/components/quick-action-menu.styl

This PR adds a "quick actions menu" in the top left of the node view.
It lets the user change the kind of variable (to test thoroughly the model settings must be for a dynamic model), and change the icon.

181336977 add quick action menu

---

src/code/stores/graph-store.ts
src/code/views/inspector-panel-view.tsx
src/code/views/relation-inspector-view.tsx

With this change only the selected link is shown in the relationship panel when there are multiple links into a node and a link is double clicked in the graph.  This also enables the link panel when a link is simply selected.
**NOTE**: this is one of the rare cases where YAGNI didn't apply.  The code was setup to handle showing only the link selected but it was stubbed out for later (now) use.

Only show selected link in relationship panel and enable link panel when link selected [#164294939] [#181336183]

---

src/code/stores/graph-store.ts

This adds a simple y offset when two nodes have crossing transfer links so that the transfer nodes don't overlay each other.

Fixed second transfer flow variable plotted right on top of the other [#181061656]

---

src/code/views/simulation-inspector-view.tsx

This fixes a couple of bugs added in a previous commit:
1. Removes direct use of props when setting the initial state to remove React warning
2. Adds a check when changing the simulation type to diagram only to auto change to basic complexity if there are no complex existing relationships
This also removes an unused import found when linting.

Fixed basic/expanded relationship radio button [#177724448]

---

src/code/utils/js-plumb-diagram-toolkit.ts

The commit that added relationship symbols to transfer links broke the placement of the relationship symbols on variable with magnitude links.

Fixed relationship symbol bug introduced after adding them to transfer links [#181337002]

---

src/stylus/app.styl
src/stylus/mixins/ordered-mixins.styl

This adds the node-z-index constants to the stylus build before the modal styles so that the z-index variable is defined for the background.  With the invalid z-index the background click handler was not being called.

Fixed z-index of modal background [#159109098]

---

src/code/utils/js-plumb-diagram-toolkit.ts

Before this change the relationship symbols were not shown for transfer modifier links as their magnitude was 0.

Add relationship symbols to transfer modifier links [#181337002]

---

src/code/stores/graph-store.ts
src/code/views/node-view.tsx

This reverts a recent change in the user menu.  This also fixes an issue where unconnected nodes converted to flow variables didn't update their image.

Remove recently added code to remove flow variable links when the node changes [#181336977]

---

src/code/stores/app-settings-store.ts
src/code/stores/graph-store.ts
src/code/views/simulation-inspector-view.tsx

This moves the to automatically update the relationship type based on the model type from the view to the store.

Fix setting of relationships when simulation type changes [#177724448]

---

src/code/stores/graph-store.ts
src/code/views/node-inspector-view.tsx
src/code/views/quick-action-menu-view.tsx
src/code/views/relation-inspector-view.tsx

- Only show create graph option for transfer nodes
- Update node image correctly when switching between node types
- Removes flow links when a node is converted to a normal node

Quick action menu tweaks [#181336977]

---

src/code/stores/graph-store.ts
src/code/stores/palette-store.ts
src/code/views/graph-view.tsx
src/code/views/node-view.tsx

- Fixed accidental removal of flow links on node change that isn't about node type
- Fixed image update to not update image info if it hasn't changed in the node
- Fixed node setting palette info for node when collector is dragged in.  This was just updating the image but leaving the uuid and useDefaultImage in the incorrect state.
- Updated node view not to "stack" node images if they are already the collector image

Omnibug bug fix after release [#181740905]

---

src/code/stores/graph-store.ts
src/code/utils/resize-image.ts
test/graph-store-test.ts

- Changed resized images from 100x100 to 50x50 as 50x50 is the maximum we ever use
- Changed graph serialization to remove duplicate image in node if it already exists in the palette

Reduce size of serialized data [#182142004]

---

src/assets/sage.html

This was using a Google project we no longer has access to and thus can't enable the Google picker on.

fix: Switch to SageModeler Google Drive project [PT-186851280]
